name: Release Electron App

on:
  push:
    tags:
      - 'v*'  # Ejecutar cuando se crea un tag (ej: v1.0.0)
    branches:
      - main  # También se puede activar en push a main

jobs:
  build-and-release:
    runs-on: windows-latest  # Necesario para builds de Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci --force

    - name: Build Electron App
      run: npm run make:win

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          out/make/squirrel.windows/x64/*.exe
          out/make/squirrel.windows/x64/RELEASES
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}